<a href="https://colab.research.google.com/github/sevcenkolera/sevcenko/blob/main/%D0%9B%D0%A01_%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%BE_%D0%92%D0%B0%D0%BB%D0%B5%D1%80%D1%96%D1%8F_%D0%A4%D0%86%D0%A24_8_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук

**Тема:** Дії з векторами та матрицями. Бібліотека NumPy.

20 завдань. Після кожної умови залишено порожню комірку для самостійного написання коду.

У наборі використано інші числові дані, а також додано нові операції з NumPy.

## Підготовка

In [1]:
import numpy as np


## Завдання 1. Додавання, віднімання та множення векторів на число

Дано вектори:
```python
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])
```

1. Знайдіть `a + b`.
2. Знайдіть `a - b`.
3. Помножте вектор `a` на число `4`.
4. Помножте вектор `b` на число `-2`.
5. Обчисліть поелементний добуток `a * b`.

In [3]:
# Задані вектори
a = np.array([7, -2, 5, 9])
b = np.array([3, 6, -1, 4])

# 1. Додавання векторів a + b
sum_ab = a + b
print("a + b =", sum_ab)

# 2. Віднімання векторів a - b
diff_ab = a - b
print("a - b =", diff_ab)

# 3. Множення вектора a на число 4
mult_a4 = a * 4
print("a * 4 =", mult_a4)

# 4. Множення вектора b на число -2
mult_b_neg2 = b * -2
print("b * (-2) =", mult_b_neg2)

# 5. Поелементний добуток a * b
prod_ab = a * b
print("Поелементний добуток a * b =", prod_ab)

a + b = [10  4  4 13]
a - b = [ 4 -8  6  5]
a * 4 = [28 -8 20 36]
b * (-2) = [ -6 -12   2  -8]
Поелементний добуток a * b = [ 21 -12  -5  36]


## Завдання 2. Скалярний добуток і довжина векторів

Дано вектори:
```python
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])
```

1. Обчисліть скалярний добуток двома способами: `np.dot()` і оператором `@`.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами.

In [4]:
# Задані вектори
u = np.array([2, -3, 6])
v = np.array([5, 1, 4])

# 1. Скалярний добуток двома способами
dot_product_1 = np.dot(u, v)
dot_product_2 = u @ v
print("Скалярний добуток (np.dot):", dot_product_1)
print("Скалярний добуток (@):", dot_product_2)

# 2. Евклідова норма (довжина) векторів
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
print("Довжина вектора u:", norm_u)
print("Довжина вектора v:", norm_v)

# 3. Косинус кута між векторами
# cos(theta) = (u . v) / (||u|| * ||v||)
cos_angle = dot_product_1 / (norm_u * norm_v)
print("Косинус кута між векторами:", cos_angle)

Скалярний добуток (np.dot): 31
Скалярний добуток (@): 31
Довжина вектора u: 7.0
Довжина вектора v: 6.48074069840786
Косинус кута між векторами: 0.6833434069749784


## Завдання 3. Основні дії з матрицями

Дано матриці:
```python
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])
```

1. Обчисліть `A + B`.
2. Обчисліть `A - B`.
3. Обчисліть поелементний добуток `A * B`.
4. Помножте матрицю `A` на число `5`.
5. Знайдіть транспоновану матрицю `A`.

In [5]:
# Задані матриці
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])

# 1. Додавання матриць A + B
add_AB = A + B
print("A + B:\n", add_AB)

# 2. Віднімання матриць A - B
sub_AB = A - B
print("A - B:\n", sub_AB)

# 3. Поелементний добуток A * B
elem_mult = A * B
print("Поелементний добуток A * B:\n", elem_mult)

# 4. Множення матриці A на число 5
mult_A5 = A * 5
print("Матриця A помножена на 5:\n", mult_A5)

# 5. Транспонування матриці A
trans_A = A.T
print("Транспонована матриця A (A.T):\n", trans_A)

A + B:
 [[4 3 5]
 [9 3 6]]
A - B:
 [[ 2  7 -7]
 [-5 -3  2]]
Поелементний добуток A * B:
 [[  3 -10  -6]
 [ 14   0   8]]
Матриця A помножена на 5:
 [[15 25 -5]
 [10  0 20]]
Транспонована матриця A (A.T):
 [[ 3  2]
 [ 5  0]
 [-1  4]]


## Завдання 4. Матричне множення

Дано матриці:
```python
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])
```

1. Обчисліть матричний добуток `A @ B`.
2. Визначте форму результату.
3. Обчисліть елемент результату з індексами `[0, 1]` вручну через відповідний рядок `A` і стовпець `B` та перевірте його.

In [6]:
# Задані матриці
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])

# 1. Матричний добуток A @ B
result = A @ B
print("Матричний добуток A @ B:\n", result)

# 2. Форма (розмірність) результату
print("Форма результату:", result.shape)

# 3. Перевірка елемента з індексами [0, 1]
# Рядок 0 матриці A: [2, 1, 3], Стовпець 1 матриці B: [2, 0, 1]
manual_val = (2 * 2) + (1 * 0) + (3 * 1)
print("Ручний розрахунок елемента [0, 1]:", manual_val)
print("Значення з матриці результату [0, 1]:", result[0, 1])

Матричний добуток A @ B:
 [[17  7]
 [32  5]]
Форма результату: (2, 2)
Ручний розрахунок елемента [0, 1]: 7
Значення з матриці результату [0, 1]: 7


## Завдання 5. Циклічний зсув вектора

Дано вектор:
```python
v = np.array([12, 7, 19, 4, 11, 8])
```

1. Виконайте циклічний зсув на 2 позиції вправо.
2. Виконайте циклічний зсув на 3 позиції вліво.
3. Відновіть початковий вектор із результату першого зсуву.

Використайте `np.roll()`.

In [7]:
# Заданий вектор
v = np.array([12, 7, 19, 4, 11, 8])

# 1. Циклічний зсув на 2 позиції вправо (додатне значення зсуву)
shift_right_2 = np.roll(v, 2)
print("Зсув на 2 позиції вправо:\n", shift_right_2)

# 2. Циклічний зсув на 3 позиції вліво (від'ємне значення зсуву)
shift_left_3 = np.roll(v, -3)
print("Зсув на 3 позиції вліво:\n", shift_left_3)

# 3. Відновлення початкового вектора з результату першого зсуву
# Оскільки робили зсув вправо на 2, для відновлення робимо зсув вліво на 2 (-2)
restored_v = np.roll(shift_right_2, -2)
print("Відновлений початковий вектор:\n", restored_v)

Зсув на 2 позиції вправо:
 [11  8 12  7 19  4]
Зсув на 3 позиції вліво:
 [ 4 11  8 12  7 19]
Відновлений початковий вектор:
 [12  7 19  4 11  8]


## Завдання 6. Сортування та індекси

Дано вектор:
```python
v = np.array([42, 17, 29, 8, 35, 23])
```

1. Відсортуйте елементи за зростанням.
2. Відсортуйте елементи за спаданням.
3. Отримайте індекси початкового вектора, які задають порядок елементів від найбільшого до найменшого.

Використайте `np.sort()` та `np.argsort()`.

In [8]:
# Заданий вектор
v = np.array([42, 17, 29, 8, 35, 23])

# 1. Сортування елементів за зростанням
sort_ascending = np.sort(v)
print("Відсортовано за зростанням:\n", sort_ascending)

# 2. Сортування елементів за спаданням
# Використовуємо зріз [::-1] для обертання відсортованого масиву
sort_descending = np.sort(v)[::-1]
print("Відсортовано за спаданням:\n", sort_descending)

# 3. Індекси початкового вектора для порядку від найбільшого до найменшого
# np.argsort() за замовчуванням сортує за зростанням, тому беремо [::-1] для спадання
args_descending = np.argsort(v)[::-1]
print("Індекси від найбільшого до найменшого (np.argsort):\n", args_descending)

Відсортовано за зростанням:
 [ 8 17 23 29 35 42]
Відсортовано за спаданням:
 [42 35 29 23 17  8]
Індекси від найбільшого до найменшого (np.argsort):
 [0 4 2 5 1 3]


## Завдання 7. Обмеження значень

Дано вектор:
```python
v = np.array([-12, -4, 3, 18, 27, 35, 48])
```

Обмежте всі значення діапазоном від `-5` до `30`: значення, менші за `-5`, мають стати `-5`, а більші за `30` — `30`.

Додатково визначте індекси елементів, які були змінені.

Використайте `np.clip()`.

In [9]:
# Заданий вектор
v = np.array([-12, -4, 3, 18, 27, 35, 48])

# 1. Обмеження значень діапазоном від -5 до 30
v_clipped = np.clip(v, -5, 30)
print("Обмежений вектор (np.clip):\n", v_clipped)

# 2. Визначення індексів елементів, які були змінені
# Порівнюємо початковий і обмежений вектори (де вони не рівні)
changed_indices = np.where(v != v_clipped)[0]
print("Індекси змінених елементів:\n", changed_indices)

Обмежений вектор (np.clip):
 [-5 -4  3 18 27 30 30]
Індекси змінених елементів:
 [0 5 6]


## Завдання 8. Унікальні значення та частоти

Дано вектор:
```python
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])
```

1. Знайдіть усі унікальні значення.
2. Визначте кількість появ кожного значення.
3. Знайдіть значення, яке трапляється найчастіше.

Використайте `np.unique(..., return_counts=True)`.

In [10]:
import numpy as np

# Заданий вектор
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])

# 1. Знаходження всіх унікальних значень та їхніх частот
unique_vals, counts = np.unique(v, return_counts=True)
print("Унікальні значення:", unique_vals)
print("Кількість появ кожного значення:", counts)

# 2. Знаходження значення, яке трапляється найчастіше
most_frequent_val = unique_vals[np.argmax(counts)]
print("Значення, яке трапляється найчастіше:", most_frequent_val)

Унікальні значення: [2 4 7 9]
Кількість появ кожного значення: [3 3 4 1]
Значення, яке трапляється найчастіше: 7


## Завдання 9. Поворот матриці

Дано матрицю:
```python
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])
```

Отримайте:
1. матрицю, повернуту на 90° за годинниковою стрілкою;
2. матрицю, повернуту на 180°;
3. матрицю, повернуту на 90° проти годинникової стрілки.

Використайте `np.rot90()`.

In [12]:

# Задана матриця
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])

# 1. Поворот на 90° за годинниковою стрілкою (k = -1)
rot_90_cw = np.rot90(A, -1)
print("Поворот на 90° за годинниковою стрілкою:\n", rot_90_cw)

# 2. Поворот на 180° (k = 2)
rot_180 = np.rot90(A, 2)
print("\nПоворот на 180°:\n", rot_180)

# 3. Поворот на 90° проти годинникової стрілки (k = 1, за замовчуванням)
rot_90_ccw = np.rot90(A, 1)
print("\nПоворот на 90° проти годинникової стрілки:\n", rot_90_ccw)

Поворот на 90° за годинниковою стрілкою:
 [[18 10  2]
 [20 12  4]
 [22 14  6]
 [24 16  8]]

Поворот на 180°:
 [[24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]

Поворот на 90° проти годинникової стрілки:
 [[ 8 16 24]
 [ 6 14 22]
 [ 4 12 20]
 [ 2 10 18]]


## Завдання 10. Додавання рамки до матриці

Дано матрицю:
```python
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])
```

1. Додайте навколо матриці рамку шириною 1 елемент, заповнену значенням `-1`.
2. Окремо створіть рамку шириною 2 елементи, заповнену нулями.
3. Виведіть форми отриманих матриць.

Використайте `np.pad()`.

In [13]:
# Задана матриця
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])

# 1. Рамка шириною 1 елемент, заповнена значенням -1
padded_minus1 = np.pad(A, pad_width=1, mode='constant', constant_values=-1)
print("Матриця з рамкою (-1):\n", padded_minus1)
print("Форма матриці з рамкою -1:", padded_minus1.shape)

# 2. Рамка шириною 2 елементи, заповнена нулями (нули є значенням за замовчуванням для mode='constant')
padded_zeros = np.pad(A, pad_width=2, mode='constant', constant_values=0)
print("\nМатриця з рамкою з нулів:\n", padded_zeros)
print("Форма матриці з рамкою з нулів:", padded_zeros.shape)

Матриця з рамкою (-1):
 [[-1 -1 -1 -1 -1]
 [-1  6  1  8 -1]
 [-1  3  5  2 -1]
 [-1  9  4  7 -1]
 [-1 -1 -1 -1 -1]]
Форма матриці з рамкою -1: (5, 5)

Матриця з рамкою з нулів:
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 6 1 8 0 0]
 [0 0 3 5 2 0 0]
 [0 0 9 4 7 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Форма матриці з рамкою з нулів: (7, 7)


## Завдання 11. Перестановка рядків і стовпців

Дано матрицю:
```python
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])
```

1. Переставте рядки відповідно до `row_order`.
2. Після цього переставте стовпці відповідно до `col_order`.
3. За допомогою обернених перестановок відновіть початкову матрицю.

Для побудови оберненої перестановки використайте `np.argsort()`.

In [14]:
# Задана матриця та вектори порядку
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])

# 1. Перестановка рядків відповідно до row_order
A_permuted_rows = A[row_order, :]

# 2. Перестановка стовпців відповідно до col_order
A_permuted = A_permuted_rows[:, col_order]
print("Матриця після перестановки рядків і стовпців:\n", A_permuted)

# 3. Відновлення початкової матриці за допомогою обернених перестановок
inv_row_order = np.argsort(row_order)
inv_col_order = np.argsort(col_order)

A_restored = A_permuted[inv_row_order, :][:, inv_col_order]
print("\nВідновлена початкова матриця:\n", A_restored)

Матриця після перестановки рядків і стовпців:
 [[34 32 31 33]
 [14 12 11 13]
 [44 42 41 43]
 [24 22 21 23]]

Відновлена початкова матриця:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


## Завдання 12. Трикутні частини матриці

Дано матрицю:
```python
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])
```

1. Отримайте верхню трикутну частину разом із головною діагоналлю.
2. Отримайте нижню трикутну частину разом із головною діагоналлю.
3. Отримайте строго верхню та строго нижню частини.
4. Відновіть початкову матрицю з нижньої та строго верхньої частин.

Використайте `np.triu()` та `np.tril()`.

In [15]:
# Задана матриця
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])

# 1. Верхня трикутна частина разом із головною діагоналлю
upper_tri = np.triu(A, k=0)
print("Верхня трикутна частина (з діагоналлю):\n", upper_tri)

# 2. Нижня трикутна частина разом із головною діагоналлю
lower_tri = np.tril(A, k=0)
print("\nНижня трикутна частина (з діагоналлю):\n", lower_tri)

# 3. Строго верхня та строго нижня частини (виключаючи головну діагональ)
strict_upper = np.triu(A, k=1)
strict_lower = np.tril(A, k=-1)
print("\nСтрого верхня частина:\n", strict_upper)
print("\nСтрого нижня частина:\n", strict_lower)

# 4. Відновлення початкової матриці
A_restored = lower_tri + strict_upper
print("\nВідновлена початкова матриця:\n", A_restored)

Верхня трикутна частина (з діагоналлю):
 [[4 1 7 2]
 [0 3 5 8]
 [0 0 6 1]
 [0 0 0 3]]

Нижня трикутна частина (з діагоналлю):
 [[4 0 0 0]
 [6 3 0 0]
 [9 2 6 0]
 [5 7 4 3]]

Строго верхня частина:
 [[0 1 7 2]
 [0 0 5 8]
 [0 0 0 1]
 [0 0 0 0]]

Строго нижня частина:
 [[0 0 0 0]
 [6 0 0 0]
 [9 2 0 0]
 [5 7 4 0]]

Відновлена початкова матриця:
 [[4 1 7 2]
 [6 3 5 8]
 [9 2 6 1]
 [5 7 4 3]]


## Завдання 13. Зовнішній добуток векторів

Дано вектори:
```python
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])
```

1. Побудуйте матрицю зовнішнього добутку.
2. Визначте її форму.
3. Перевірте, що елемент `[2, 1]` дорівнює `a[2] * b[1]`.

Використайте `np.outer()`.

In [16]:
# Задані вектори
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])

# 1. Побудова матриці зовнішнього добутку
outer_product = np.outer(a, b)
print("Матриця зовнішнього добутку:\n", outer_product)

# 2. Визначення форми отриманої матриці
print("Форма матриці:", outer_product.shape)

# 3. Перевірка елемента [2, 1]
print("Значення матриці в [2, 1]:", outer_product[2, 1])
print("Значення a[2] * b[1]:", a[2] * b[1])
print("Збігаються:", outer_product[2, 1] == a[2] * b[1])

Матриця зовнішнього добутку:
 [[ 6 10 16]
 [12 20 32]
 [21 35 56]
 [27 45 72]]
Форма матриці: (4, 3)
Значення матриці в [2, 1]: 35
Значення a[2] * b[1]: 35
Збігаються: True


## Завдання 14. Добуток Кронекера

Дано матриці:
```python
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])
```

1. Обчисліть добуток Кронекера `A` і `B`.
2. Обчисліть добуток Кронекера `B` і `A`.
3. Порівняйте результати та їх форми.

Використайте `np.kron()`.

In [17]:
# Задані матриці
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])

# 1. Добуток Кронекера A і B
kron_ab = np.kron(A, B)
print("Добуток Кронекера A ⊗ B:\n", kron_ab)

# 2. Добуток Кронекера B і A
kron_ba = np.kron(B, A)
print("\nДобуток Кронекера B ⊗ A:\n", kron_ba)

# 3. Порівняння результатів та форм
print("\nФорма A ⊗ B:", kron_ab.shape)
print("Форма B ⊗ A:", kron_ba.shape)
print("Чи рівні матриці результатів?:", np.array_equal(kron_ab, kron_ba))

Добуток Кронекера A ⊗ B:
 [[ 2  8  1  4]
 [ 4  0  2  0]
 [ 0  0  3 12]
 [ 0  0  6  0]]

Добуток Кронекера B ⊗ A:
 [[ 2  1  8  4]
 [ 0  3  0 12]
 [ 4  2  0  0]
 [ 0  6  0  0]]

Форма A ⊗ B: (4, 4)
Форма B ⊗ A: (4, 4)
Чи рівні матриці результатів?: False


## Завдання 15. Комутатор двох матриць

Для кожної пари матриць обчисліть комутатор
\[
[A,B] = AB - BA.
\]

Перша пара:
```python
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])
```

Друга пара:
```python
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])
```

Визначте, для якої пари виконується `AB = BA`. Для перевірки використайте `np.allclose()`.

In [18]:
# Перша пара матриць
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])

# Друга пара матриць
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])

# 1. Обчислення комутатора для першої пари: [A1, B1] = A1 @ B1 - B1 @ A1
commutator_1 = (A1 @ B1) - (B1 @ A1)
print("Комутатор першої пари:\n", commutator_1)

# Перевірка комутативності (AB = BA) для першої пари
is_commutative_1 = np.allclose(A1 @ B1, B1 @ A1)
print("Чи виконується A1 @ B1 = B1 @ A1 для першої пари?:", is_commutative_1)

# 2. Обчислення комутатора для другої пари: [A2, B2] = A2 @ B2 - B2 @ A2
commutator_2 = (A2 @ B2) - (B2 @ A2)
print("\nКомутатор другої пари:\n", commutator_2)

# Перевірка комутативності для другої пари
is_commutative_2 = np.allclose(A2 @ B2, B2 @ A2)
print("Чи виконується A2 @ B2 = B2 @ A2 для другої пари?:", is_commutative_2)

Комутатор першої пари:
 [[0 0]
 [0 0]]
Чи виконується A1 @ B1 = B1 @ A1 для першої пари?: True

Комутатор другої пари:
 [[ 0 -6]
 [-3  0]]
Чи виконується A2 @ B2 = B2 @ A2 для другої пари?: False


## Завдання 16. Квадратична форма

Дано симетричну матрицю:
```python
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])
```

1. Обчисліть квадратичну форму `xᵀAx`.
2. Для трьох векторів
```python
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])
```
обчисліть значення квадратичної форми для кожного рядка без циклу.

Для другого пункту використайте `np.einsum()`.

In [19]:
# Симетрична матриця та початковий вектор
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])

# 1. Обчислення квадратичної форми xᵀAx для одного вектора
quad_form_single = x.T @ A @ x
print("Значення квадратичної форми для вектора x:", quad_form_single)

# 2. Матриця рядків-векторів
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])

# Обчислення квадратичної форми для кожного рядка без циклу за допомогою np.einsum()
# 'ij,jk,ik->i' означає: множимо елементи X (ij) на A (jk) і на X (ik), а потім сумуємо по індексу j (отримуємо вектор по i)
quad_forms_vectorized = np.einsum('ij,jk,ik->i', X, A, X)
print("Значення квадратичної форми для кожного рядка (np.einsum):\n", quad_forms_vectorized)

Значення квадратичної форми для вектора x: 35
Значення квадратичної форми для кожного рядка (np.einsum):
 [35 17 27]


## Завдання 17. Степінь матриці

Дано матрицю:
```python
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])
```

1. Обчисліть `A²`.
2. Обчисліть `A³`.
3. Перевірте, що `A³ = A² @ A`.

Використайте `np.linalg.matrix_power()`.

In [20]:
# Задана матриця
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])

# 1. Обчислення квадрат матриці (A²)
A2 = np.linalg.matrix_power(A, 2)
print("Матриця A²:\n", A2)

# 2. Обчислення куба матриці (A³)
A3 = np.linalg.matrix_power(A, 3)
print("\nМатриця A³:\n", A3)

# 3. Перевірка, що A³ = A² @ A
is_equal = np.array_equal(A3, A2 @ A)
print("\nЧи виконується умова A³ = A² @ A?:", is_equal)

Матриця A²:
 [[1 2 1]
 [1 1 2]
 [2 1 1]]

Матриця A³:
 [[2 3 3]
 [3 2 3]
 [3 3 2]]

Чи виконується умова A³ = A² @ A?: True


## Завдання 18. Ранг матриці

Дано дві матриці:
```python
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])
```

1. Знайдіть ранг кожної матриці.
2. Визначте, яка з них має повний ранг.

Використайте `np.linalg.matrix_rank()`.

In [21]:
# Задані матриці
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])

# 1. Знаходження рангу кожної матриці
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)
print("Ранг матриці A:", rank_A)
print("Ранг матриці B:", rank_B)

# 2. Визначення повного рангу (матриця 3x3 має повний ранг, якщо її ранг дорівнює 3)
full_rank_A = (rank_A == min(A.shape))
full_rank_B = (rank_B == min(B.shape))

print("Матриця A має повний ранг:", full_rank_A)
print("Матриця B має повний ранг:", full_rank_B)

Ранг матриці A: 3
Ранг матриці B: 2
Матриця A має повний ранг: True
Матриця B має повний ранг: False


## Завдання 19. Власні значення та власні вектори

Дано симетричну матрицю:
```python
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])
```

1. Знайдіть власні значення та власні вектори.
2. Перевірте співвідношення `A @ V = V * λ`.
3. Виведіть результат перевірки через `np.allclose()`.

Використайте `np.linalg.eigh()`.

In [22]:
# Задана симетрична матриця
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])

# 1. Знаходження власних значень та власних векторів для симетричної матриці
eigenvalues, eigenvectors = np.linalg.eigh(A)
print("Власні значення (λ):\n", eigenvalues)
print("\nВласні вектори (V):\n", eigenvectors)

# 2. Перевірка співвідношення A @ V = V * λ
# У NumPy поелементне множення або множення матриці на діагональну матрицю
# Лівa частина: A @ V
left_side = A @ eigenvectors

# Права частина: V * eigenvalues (множить кожен стовпчик V на відповідне власне значення)
right_side = eigenvectors * eigenvalues

# 3. Перевірка через np.allclose()
is_correct = np.allclose(left_side, right_side)
print("\nРезультат перевірки A @ V = V * λ (np.allclose):", is_correct)

Власні значення (λ):
 [2. 7.]

Власні вектори (V):
 [[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]

Результат перевірки A @ V = V * λ (np.allclose): True


## Завдання 20. Метод найменших квадратів

Для точок
```python
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])
```

побудуйте пряму
\[
y \approx a + bx.
\]

1. Сформуйте матрицю ознак зі стовпця одиниць і значень `x`.
2. Знайдіть коефіцієнти `a` і `b` методом найменших квадратів.
3. Обчисліть прогнозні значення `y`.
4. Знайдіть суму квадратів залишків.

Використайте `np.linalg.lstsq()`.

In [23]:
# Задані точки
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])

# 1. Створення матриці ознак (Design matrix), що складається зі стовпця одиниць (для вільного члена a) та x
X_mat = np.vstack([np.ones_like(x), x]).T
print("Матриця ознак X:\n", X_mat)

# 2. Знаходження коефіцієнтів a і b методом найменших квадратів
# np.linalg.lstsq повертає масив коефіцієнтів [a, b], залишки, ранг та сингулярні значення
coeffs, residuals, rank, s = np.linalg.lstsq(X_mat, y, rcond=None)
a, b = coeffs
print(f"Знайдені коефіцієнти: a = {a:.4f}, b = {b:.4f}")

# 3. Обчислення прогнозних значень y_pred
y_pred = X_mat @ coeffs
print("Прогнозні значення y:", y_pred)

# 4. Обчислення суми квадратів залишків
# Якщо residuals порожній (для надлишкових систем він повертається автоматично), обчислюємо вручну
sum_residuals = residuals[0] if residuals.size > 0 else np.sum((y - y_pred) ** 2)
print("Сума квадратів залишків:", sum_residuals)

Матриця ознак X:
 [[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]]
Знайдені коефіцієнти: a = 2.0200, b = 2.0100
Прогнозні значення y: [ 2.02  4.03  6.04  8.05 10.06]
Сума квадратів залишків: 0.13100000000000012
