<a href="https://colab.research.google.com/github/sevcenkolera/sevcenko/blob/main/%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%BE__hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Імпорт бібліотеки NumPy
import numpy as np

In [2]:
# 1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення

vector_20 = np.arange(1, 21)
vector_20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
# Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення

matrix_4x4 = np.ones((4, 4))
matrix_4x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
# Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення

matrix_5x5 = np.random.uniform(-1, 1, (5, 5))
matrix_5x5

array([[ 0.75598202,  0.55447757, -0.93645054,  0.46944648, -0.86249296],
       [-0.37121714,  0.3137982 , -0.96317555, -0.5303305 , -0.97472472],
       [-0.32044739, -0.47551323,  0.6287495 ,  0.9470753 , -0.89668272],
       [-0.67942297, -0.88413067, -0.58589545,  0.3956634 ,  0.92115426],
       [ 0.26774061, -0.18577696, -0.66063788,  0.67117876, -0.68624837]])

In [5]:
# Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення

matrix_3x3 = np.random.rand(3, 3)
matrix_3x3

array([[0.51679985, 0.51773857, 0.92809239],
       [0.14122894, 0.708785  , 0.82553488],
       [0.86846353, 0.45520863, 0.66918272]])

In [6]:
# Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20
# та виконайте на них поелементні операції додавання, віднімання та множення

arr1 = np.random.randint(1, 21, 6)
arr2 = np.random.randint(1, 21, 6)

sum_arr = arr1 + arr2
sub_arr = arr1 - arr2
mul_arr = arr1 * arr2

arr1, arr2, sum_arr, sub_arr, mul_arr


(array([16,  8,  7, 15, 15, 18]),
 array([19, 10, 15, 17, 14, 12]),
 array([35, 18, 22, 32, 29, 30]),
 array([-3, -2, -8, -2,  1,  6]),
 array([304,  80, 105, 255, 210, 216]))

In [7]:
# Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5
# та перемножте їх між собою

matrix_a = np.random.randint(1, 6, (3, 2))
matrix_b = np.random.randint(1, 6, (2, 4))

result_multiply = np.dot(matrix_a, matrix_b)

matrix_a, matrix_b, result_multiply


(array([[1, 1],
        [3, 4],
        [4, 3]]),
 array([[3, 3, 3, 5],
        [5, 2, 1, 2]]),
 array([[ 8,  5,  4,  7],
        [29, 17, 13, 23],
        [27, 18, 15, 26]]))

In [8]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її

matrix_random = np.random.rand(3, 3)
matrix_transposed = matrix_random.T

matrix_random, matrix_transposed


(array([[0.66333896, 0.49741405, 0.97031304],
        [0.46582478, 0.15950957, 0.90807585],
        [0.17697469, 0.59400667, 0.44888246]]),
 array([[0.66333896, 0.46582478, 0.17697469],
        [0.49741405, 0.15950957, 0.59400667],
        [0.97031304, 0.90807585, 0.44888246]]))

In [9]:
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
# та знайдіть їхню різницю

matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))

difference = matrix1 - matrix2

matrix1, matrix2, difference


(array([[3, 8, 2],
        [5, 5, 5],
        [4, 3, 5]]),
 array([[ 2, 10,  4],
        [ 1, 10, 10],
        [ 8,  5,  1]]),
 array([[ 1, -2, -2],
        [ 4, -5, -5],
        [-4, -2,  4]]))

In [10]:
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5
# та знайдіть їх добуток

matrix3 = np.random.randint(-5, 6, (3, 3))
matrix4 = np.random.randint(-5, 6, (3, 3))

product = np.dot(matrix3, matrix4)

matrix3, matrix4, product

(array([[-3, -2,  1],
        [-3,  2, -3],
        [ 0, -2, -4]]),
 array([[-3,  3, -2],
        [ 0, -3,  4],
        [-2, -5, -3]]),
 array([[ 7, -8, -5],
        [15,  0, 23],
        [ 8, 26,  4]]))

In [11]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1
# та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці

matrix_final = np.random.uniform(-1, 1, (3, 3))
row_sums = matrix_final.sum(axis=1).reshape(3, 1)

matrix_final, row_sums

(array([[-0.53988538,  0.24821808, -0.85158074],
        [ 0.89186559,  0.16262236,  0.537525  ],
        [ 0.01156989, -0.52182022,  0.09904521]]),
 array([[-1.14324804],
        [ 1.59201295],
        [-0.41120512]]))